name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: generate github-contribution-grid-snake.svg (light)
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: caio-sp
          outputs: dist/github-contribution-grid-snake.svg

      - name: generate github-contribution-grid-snake.svg (dark)
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: caio-sp
          palette: github-dark
          outputs: dist/github-contribution-grid-snake-dark.svg

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
