name: generate animation

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake SVG
        uses: Platane/snk/svg-only@v1
        with:
          github_user_name: caio-sp
          outputs: dist/github-contribution-grid-snake.svg
